# Generated by Django 5.0.6 on 2024-06-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_investorid_investor_investorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='investorid',
            new_name='investor_id',
        ),
    ]
