# Generated by Django 5.0.6 on 2024-06-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_investorid_investor_investor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_deposit', models.IntegerField()),
                ('min_holding_term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('multiplier', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='holdings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investor',
            name='referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Acccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.investor')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account_type')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.level')),
            ],
        ),
    ]
