# Generated by Django 5.0.6 on 2024-06-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account_type_level_investor_holdings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acccount',
            new_name='Account',
        ),
    ]
