# Generated by Django 5.0.6 on 2024-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_type',
            name='return_rate',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
