# Generated by Django 5.0.6 on 2024-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_account_type_return_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
