# Generated by Django 5.0.6 on 2024-06-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_account_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
