# Generated by Django 5.0.6 on 2024-06-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_account_activation_date_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='eroi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
