# Generated by Django 5.0.6 on 2024-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
