# Generated by Django 5.0.6 on 2024-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_account_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
