# Generated by Django 5.0.6 on 2024-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_investor_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='level',
            field=models.CharField(default='Silver', max_length=10),
        ),
    ]
