# Generated by Django 5.0.6 on 2024-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_investor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_type',
            name='about',
            field=models.TextField(default='type', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account_type',
            name='link',
            field=models.SlugField(default='alu', max_length=80),
            preserve_default=False,
        ),
    ]
