# Generated by Django 5.0.6 on 2024-06-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_account_type_about_account_type_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_type',
            name='is_alternate',
            field=models.BooleanField(default=False),
        ),
    ]
