# Generated by Django 5.0.6 on 2024-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_account_type_is_alternate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_type',
            name='is_alternate',
            field=models.BooleanField(),
        ),
    ]
