# Generated by Django 5.0.6 on 2024-10-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_support_investor_has_new_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('error', models.TextField()),
            ],
        ),
    ]
