# Generated by Django 5.0.6 on 2024-10-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='code',
            field=models.CharField(default='256372', max_length=7),
            preserve_default=False,
        ),
    ]
